/** Declaration file generated by dts-gen */

declare module 'react-router-bootstrap' {
	export function IndexLinkContainer(props: any): any;

	export function LinkContainer(props: any): any;

	export namespace IndexLinkContainer {
		class WrappedComponent {
			constructor(...args: any[]);

			render(): any;
		}

		const displayName: string;

		function apply(p0: any, p1: any): any;

		function bind(p0: any): any;

		function call(p0: any): any;

		namespace propTypes {
			function wrappedComponentRef(
				p0: any,
				p1: any,
				p2: any,
				p3: any,
				p4: any,
				p5: any
			): any;

			namespace wrappedComponentRef {
				function isRequired(
					p0: any,
					p1: any,
					p2: any,
					p3: any,
					p4: any,
					p5: any
				): any;
			}
		}
	}

	export namespace LinkContainer {
		class WrappedComponent {
			constructor(...args: any[]);

			render(): any;

			static defaultProps: {
				activeClassName: string;
				exact: boolean;
				replace: boolean;
				strict: boolean;
			};
		}

		const displayName: string;

		function apply(p0: any, p1: any): any;

		function bind(p0: any): any;

		function call(p0: any): any;

		namespace WrappedComponent {
			namespace propTypes {
				function activeClassName(
					p0: any,
					p1: any,
					p2: any,
					p3: any,
					p4: any,
					p5: any
				): any;

				function activeStyle(
					p0: any,
					p1: any,
					p2: any,
					p3: any,
					p4: any,
					p5: any
				): any;

				function children(
					p0: any,
					p1: any,
					p2: any,
					p3: any,
					p4: any,
					p5: any
				): any;

				function className(
					p0: any,
					p1: any,
					p2: any,
					p3: any,
					p4: any,
					p5: any
				): any;

				function exact(
					p0: any,
					p1: any,
					p2: any,
					p3: any,
					p4: any,
					p5: any
				): any;

				function history(
					p0: any,
					p1: any,
					p2: any,
					p3: any,
					p4: any,
					p5: any
				): any;

				function isActive(
					p0: any,
					p1: any,
					p2: any,
					p3: any,
					p4: any,
					p5: any
				): any;

				function location(
					p0: any,
					p1: any,
					p2: any,
					p3: any,
					p4: any,
					p5: any
				): any;

				function match(
					p0: any,
					p1: any,
					p2: any,
					p3: any,
					p4: any,
					p5: any
				): any;

				function onClick(
					p0: any,
					p1: any,
					p2: any,
					p3: any,
					p4: any,
					p5: any
				): any;

				function replace(
					p0: any,
					p1: any,
					p2: any,
					p3: any,
					p4: any,
					p5: any
				): any;

				function staticContext(
					p0: any,
					p1: any,
					p2: any,
					p3: any,
					p4: any,
					p5: any
				): any;

				function strict(
					p0: any,
					p1: any,
					p2: any,
					p3: any,
					p4: any,
					p5: any
				): any;

				function style(
					p0: any,
					p1: any,
					p2: any,
					p3: any,
					p4: any,
					p5: any
				): any;

				function to(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;

				namespace activeClassName {
					// Too-deep object hierarchy from react_router_bootstrap.LinkContainer.WrappedComponent.propTypes.activeClassName
					const isRequired: any;
				}

				namespace activeStyle {
					// Too-deep object hierarchy from react_router_bootstrap.LinkContainer.WrappedComponent.propTypes.activeStyle
					const isRequired: any;
				}

				namespace className {
					// Too-deep object hierarchy from react_router_bootstrap.LinkContainer.WrappedComponent.propTypes.className
					const isRequired: any;
				}

				namespace exact {
					// Too-deep object hierarchy from react_router_bootstrap.LinkContainer.WrappedComponent.propTypes.exact
					const isRequired: any;
				}

				namespace isActive {
					// Too-deep object hierarchy from react_router_bootstrap.LinkContainer.WrappedComponent.propTypes.isActive
					const isRequired: any;
				}

				namespace location {
					// Too-deep object hierarchy from react_router_bootstrap.LinkContainer.WrappedComponent.propTypes.location
					const isRequired: any;
				}

				namespace match {
					// Too-deep object hierarchy from react_router_bootstrap.LinkContainer.WrappedComponent.propTypes.match
					const isRequired: any;
				}

				namespace onClick {
					// Too-deep object hierarchy from react_router_bootstrap.LinkContainer.WrappedComponent.propTypes.onClick
					const isRequired: any;
				}

				namespace replace {
					// Too-deep object hierarchy from react_router_bootstrap.LinkContainer.WrappedComponent.propTypes.replace
					const isRequired: any;
				}

				namespace staticContext {
					// Too-deep object hierarchy from react_router_bootstrap.LinkContainer.WrappedComponent.propTypes.staticContext
					const isRequired: any;
				}

				namespace strict {
					// Too-deep object hierarchy from react_router_bootstrap.LinkContainer.WrappedComponent.propTypes.strict
					const isRequired: any;
				}

				namespace style {
					// Too-deep object hierarchy from react_router_bootstrap.LinkContainer.WrappedComponent.propTypes.style
					const isRequired: any;
				}
			}
		}

		namespace propTypes {
			function wrappedComponentRef(
				p0: any,
				p1: any,
				p2: any,
				p3: any,
				p4: any,
				p5: any
			): any;

			namespace wrappedComponentRef {
				function isRequired(
					p0: any,
					p1: any,
					p2: any,
					p3: any,
					p4: any,
					p5: any
				): any;
			}
		}
	}
}
